export const SET_EXAMS_LIST = 'SET_BUCKETS_LIST'
export const SET_EXAMS_LIST_LOADING = 'SET_BUCKETS_LIST_LOADING'
export const SET_SESSION_TEST_LIST = 'SET_SESSION_TEST_LIST'
export const SET_SOURCES_LIST = 'SET_SOURCES_LIST'

export const SET_STATUS_LIST ='SET_STATUS_LIST';
export const ADD_STATUS = 'ADD_STATUS';
export const EDIT_STATUS = 'EDIT_STATUS';
export const DELETE_STATUS = 'DELETE_STATUS';

export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';


export const SET_EXAMS_LIST_ERROR = 'SET_EXAMS_LIST_ERROR';
export const SET_SOURCES_LIST_ERROR = 'SET_SOURCES_LIST_ERROR';
