export const SET_EXAMS_LIST = 'SET_BUCKETS_LIST'
export const SET_EXAMS_LIST_LOADING = 'SET_BUCKETS_LIST_LOADING'
export const SET_SESSION_TEST_LIST = 'SET_SESSION_TEST_LIST'
export const SET_SOURCES_LIST = 'SET_SOURCES_LIST'
